print('BRIDGEKEEPER: Stop.')
print('Who would cross the Bridge of Death must answer me these questions three.')
print('BRIDGEKEEPER: What is your name?')
name = input()
print('BRIDGEKEEPER: What is your quest?')
quest = input()
print('BRIDGEKEEPER: What is your favorite color?')
color = input()
print('----------')
print('Traveler info:')
print(f'Your name is {name}')
print(f'Your quest is {quest}')
print(f'Your favorite color is {color}')
print('----------')
print('BRIDGEKEEPER: Right. Off you go.')